### ISSUE TITLE
ubuntu windows wsl2 and Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by Motophan** [JakeTurner616/FitGirl-Repack-List#2]
Reading package lists... Done
Building dependency tree
Reading state information... Done
lynx is already the newest version (2.9.0dev.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Can't Access `file://localhost/root/test2.html'
Alert!: Unable to access document.

lynx: Can't access startfile

Can't Access `file://localhost/root/test2.html'
Alert!: Unable to access document.

lynx: Can't access startfile

Can't Access `file://localhost/root/test2.html'
Alert!: Unable to access document.

lynx: Can't access startfile

Can't Access `file://localhost/root/test2.html'
Alert!: Unable to access document.

lynx: Can't access startfile

:(

**Comment by JakeTurner616** [comment]
Looks like a config issue when I [googled it](https://superuser.com/questions/373174/lynx-program-failing-with-cant-access-startfile). I've never run into this problem when starting lynx, but then again I run it on a Debian machine. Here is what I have as my startfile entry in my /etc/lynx/lynx.cfg: 
```
.h2 STARTFILE
# STARTFILE is the default starting URL if none is specified
#   on the command line or via a WWW_HOME environment variable;
#   Lynx will refuse to start without a starting URL of some kind.
# STARTFILE can be remote, e.g. http://www.w3.org/default.html ,
#                or local, e.g. file://localhost/PATH_TO/FILENAME ,
#           where PATH_TO is replaced with the complete path to FILENAME
#           using Unix shell syntax and including the device on VMS.
#
# Normally we expect you will connect to a remote site, e.g., the Lynx starting
# site:
#STARTFILE:https://lynx.invisible-island.net/
#
# As an alternative, you may want to use a local URL.  A good choice for this is
# the user's home directory:
.ex
#STARTFILE:file://localhost/~/
STARTFILE:file://localhost/usr/share/doc/lynx/lynx_help/about_lynx.html.gz
#
# Your choice of STARTFILE should reflect your site's needs, and be a URL that
# you can connect to reliably.  Otherwise users will become confused and think
# that they cannot run Lynx.


```

**Comment by Motophan** [comment]
Thanks for your quick response. 
I tried debian wsl2 and virtualbox debian. 
These were fresh installs, installed today. 

Maybe you are running a older version of debian. I have tried debian 12.
Same issue for ubuntu latest lts fresh wsl2 and virtualbox

I edited the lynx.cfg in all the situations and it still does not help. 
I am running the script as the highest permissions possible, logged in as the root user and also as a regular user with sudo group permissions. 

I will try debian 11 and then debian 10 until I find one that will work.
Thanks for your time

**Comment by Motophan** [comment]
Debian 11 no go, trying debian 10 now.

**Comment by Motophan** [comment]
10, 9 dont work either. I dont think you are still on debian 8. 
:(

**Comment by JakeTurner616** [comment]
Sorry about the troubles you're running into with lynx. lynx was plug-and-play for me, and yes I am using an older version of both debian and lynx. I'm on Debian 10. here my lynx --version output: `` Lynx Version 2.8.9rel.1 (08 Jul 2018)
libwww-FM 2.14, SSL-MM 1.4.1, GNUTLS 3.6.7, ncurses 6.1.20181013(wide)
Built on linux-gnu.`` 
Running ``lynx`` on an elevated shell I'm greeted by the lynx about page. If you're desperate you can try to build lynx from source using the exact version that I'm on if you're absolutely sure it's some sort of version conflict: 
```
wget https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.bz2

tar xvjf lynx2.8.9rel.1.tar.bz2

cd lynx2.8.9rel.1/

./configure --prefix=/usr && make && make install-full
```

**Comment by Motophan** [comment]
I ended up having to edit the script line w/ apt install lynx with a comment but it still shows the same error. 
for lynx I had to use `--with-ssl` and have libssl-dev installed befoer I could acsess https sites, which fitgirl is.

![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/923dec56-4f8b-4095-8e2b-deeb9b8a98c6)
and lynx https://google.com (note https)
![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/0f0dc5fb-b343-45b2-85cd-52fa875d5c54)


I used the startfile you recommended, but that didnt work. 
![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/dcda959c-6d20-4115-9d3c-39cd23cbb611)

![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/178afaf0-3b03-4849-b659-08aebada6afd)
This is `lynx file://localhost`
I emailed you, is it possible for you just to send the magnet links over. I can manually add new files as they are added via fingers. I know its not ideal. 

Alternatively if possible could you spin up a debian vm w/ no gui and run it, then you could see what is going on. 
Sorry for the trouble but I dont install anything else to the vm and it does this. We even have the same lynx version, etc. 

it doesnt try to create test2.html, I never see that file being created so lynx cant find it.
![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/a8197353-7090-436c-99ce-8877291ccf51)

**Comment by Motophan** [comment]
![image](https://github.com/JakeTurner616/FitGirl-Repack-List/assets/42502676/a48b7c32-2245-4b83-9f3c-843f08663aa4)
I had a thought it may be a cloudflare / cdn / isp block but it is not as I can navigate, using `lynx https://thesite` where `thesite` is the site we are talking about.

**Comment by JakeTurner616** [comment]
I think I see now what you're trying to achieve with this but let me know if I'm missing something. This script (Fitgirl-Repack-List) was never intended to isolate the magnet links themselves rather their parent pages to archive them directly, so this being said I think I can put together something to isolate the magnet links quite easily. Since you want to go deeper than one link at a time (to get the magnets out), a script built with lynx for all intents and purposes is over complicated because all I was doing with it was scripting information out of each page's source. Here is the exact same concept but written in python with BeautifulSoup instead. It might not be perfect but I can much more easily mess with an implementation like this if you need anything done to it! Depending on how you want to send this data you could write a save function or simply | tee out.txt it or whatever else to get it into a text file! Please let me know how it goes.

```
python --version
Python 3.9.13
```

 ```

import requests
from bs4 import BeautifulSoup

# Base URL
base_url = "https://fitgirl-repacks.site/all-my-repacks-a-z/"

# Iterate over pages 1 to 71
for page_num in range(1, 72):
    # Update the URL with the current page number
    url = base_url + f"?lcp_page0={page_num}#lcp_instance_0"

    # Send a GET request to the website and retrieve the HTML content
    response = requests.get(url)
    html_content = response.text

    # Create a BeautifulSoup object to parse the HTML
    soup = BeautifulSoup(html_content, "html.parser")

    # Find the <ul> element with class "lcp_catlist" and id "lcp_instance_0"
    ul_element = soup.find("ul", class_="lcp_catlist", id="lcp_instance_0")

    # Check if the ul_element is None
    if ul_element is not None:
        # Iterate over each <li> element within the <ul> element
        for li_element in ul_element.find_all("li"):
            # Find the <a> element within the <li> element
            a_element = li_element.find("a")
            if a_element:
                # Extract the href attribute value (link)
                link = a_element["href"]
                print("Link:", link)
                # Extract the text (title) within the <a> element
                title = a_element.text
                print("Title:", title)

                # Send a GET request to the linked page and retrieve the HTML content
                linked_page_response = requests.get(link)
                linked_page_html_content = linked_page_response.text

                # Create another BeautifulSoup object to parse the linked page's HTML
                linked_page_soup = BeautifulSoup(linked_page_html_content, "html.parser")

                # Find the <a> element with href starting with "magnet:"
                magnet_link = linked_page_soup.find("a", href=lambda href: href and href.startswith("magnet:"))
                if magnet_link:
                    # Extract the href attribute value (magnet link)
                    magnet = magnet_link["href"]
                    print("Magnet:", magnet)

                print("--------------------")
    else:
        print(f"Could not find the <ul> element with class 'lcp_catlist' and id 'lcp_instance_0' on page {page_num}")

```

**Comment by Motophan** [comment]
This is *exactly* what I needed

I have a reward for you if you email me. I cannot post it publicly, and you have my email (starts with r and ends with t, at protonmail). I emailed you on your website. 

I can now spin up seedboxes that seed all of their releases at once. 
Very nice. 

You should make this into a repo.
Great stuff

**Comment by JakeTurner616** [comment]
Thanks I appreciate it. But I want to make sure this works for you as you intend. I dunno what exactly went wrong but mine errored out after about 15 minutes or so 

```
PS C:\Users\jaked\Documents\repacklist> & C:/Python311/python.exe c:/Users/jaked/Documents/repacklist/search.py > out.txt
Traceback (most recent call last):
  File "c:\Users\jaked\Documents\repacklist\search.py", line 34, in <module>
    print("Title:", title)
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f642' in position 46: character maps to <undefined>

```

**Comment by Motophan** [comment]
isnt that just a non-unicode character? 
can u make it run w/ utf-8 ?

**Comment by JakeTurner616** [comment]
> isnt that just a non-unicode character? can u make it run w/ utf-8 ?

I think that was it! Here is an updated version that simply encodes the output using UTF-8.

```
import requests
from bs4 import BeautifulSoup

# Base URL
base_url = "https://fitgirl-repacks.site/all-my-repacks-a-z/"

# Iterate over pages 1 to 71
for page_num in range(1, 72):
    # Update the URL with the current page number
    url = base_url + f"?lcp_page0={page_num}#lcp_instance_0"

    # Send a GET request to the website and retrieve the HTML content
    response = requests.get(url)
    html_content = response.text

    # Create a BeautifulSoup object to parse the HTML
    soup = BeautifulSoup(html_content, "html.parser")

    # Find the <ul> element with class "lcp_catlist" and id "lcp_instance_0"
    ul_element = soup.find("ul", class_="lcp_catlist", id="lcp_instance_0")

    # Check if the ul_element is None
    if ul_element is not None:
        # Iterate over each <li> element within the <ul> element
        for li_element in ul_element.find_all("li"):
            # Find the <a> element within the <li> element
            a_element = li_element.find("a")
            if a_element:
                # Extract the href attribute value (link)
                link = a_element["href"]
                print("Link:", link.encode('utf-8').decode())

                # Extract the text (title) within the <a> element
                title = a_element.text
                print("Title:", title.encode('utf-8').decode())

                # Send a GET request to the linked page and retrieve the HTML content
                linked_page_response = requests.get(link)
                linked_page_html_content = linked_page_response.text

                # Create another BeautifulSoup object to parse the linked page's HTML
                linked_page_soup = BeautifulSoup(linked_page_html_content, "html.parser")

                # Find the <a> element with href starting with "magnet:"
                magnet_link = linked_page_soup.find("a", href=lambda href: href and href.startswith("magnet:"))
                if magnet_link:
                    # Extract the href attribute value (magnet link)
                    magnet = magnet_link["href"]
                    print("Magnet:", magnet.encode('utf-8').decode())

                print("--------------------")
    else:
        print(f"Could not find the <ul> element with class 'lcp_catlist' and id 'lcp_instance_0' on page {page_num}")
```

**Comment by JakeTurner616** [comment]
Mine took a while but it finished A-Z! It required a fix for the character(s): ":)" to complete all the way with the titles. Here is the [repo](https://github.com/JakeTurner616/FitGirl-Magnet-List) you suggested with the fix I mentioned. I'm also curious how you plan to get all this data into a torrent client? Awesome project btw.

**Comment by Motophan** [comment]
its the stupidest thing ever. Its just using existing tech and copying pasting
0 -> just have a big zfs / btrfs pool to handle the quantity of data. Add a cache layer to deal w/ bursts of data or just let it brr for a week.
1 -> get all the magnet links sanitized
`sed -n 's/.*\(magnet:.*\)&dn=.*/\1/p' ~/output.txt`
2 -> seperate the sanitized list into files w/ 100 links in them (the http post max for qbittorrent)
```
#!/bin/bash

file="output.txt"
output_dir="output_directory"
lines_per_file=100

mkdir -p "$output_dir" # Create the output directory if it doesn't exist

line_count=0
file_count=1
output_file="$output_dir/file$(printf "%02d" "$file_count").txt"

while IFS= read -r line; do
    if [[ $line_count -eq 0 ]]; then
        echo "$line" > "$output_file"
    else
        echo "$line" >> "$output_file"
    fi

    line_count=$((line_count + 1))

    if [[ $line_count -eq $lines_per_file ]]; then
        line_count=0
        file_count=$((file_count + 1))
        output_file="$output_dir/file$(printf "%02d" "$file_count").txt"
    fi
done < "$file"
```

3 -> install qbittorrent, setup sane queuing based on your arrays performance. Defaults are fine but you will need to come back when it gets stuck on files that wont download. Setup qbit to add https://github.com/ngosang/trackerslist best (20) trackers. Set speed limit if your array wont be able to handle your internet speed if you went cache-less and have really good internet. Install a vpn if you live in a country where you need one and check for leaks before firing this up.  

4 -> go to qbittorrents webui, paste 100 links at a time, do this 20 times

5 -> wait a while

profit

**Comment by JakeTurner616** [comment]
That is completely awesome and insanely generous. Good luck!
